[[redirects]]
  from = "/"
  to = "/es"
  status = 301
  force = true
  conditions = {Country = ["AR", "CL"]}

[[redirects]]
  from = "/"
  to = "/pt"
  status = 301
  force = true
  conditions = {Country = ["BR"]}
